# Generated by Django 3.2.3 on 2021-06-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uploaded',
            new_name='updated',
        ),
    ]
